---
version: "3"
services:
  bb-rsi-naive-initial:
    image: freqtradeorg/freqtrade:stable_pi
    restart: unless-stopped
    container_name: bb-rsi-naive-initial
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/bb-rsi-naive-initial.tradesv3.sqlite
      --config /freqtrade/user_data/bb-rsi-naive-initial.config.json
      --strategy BBRSINaiveStrategy

  bb-rsi-naive-defi:
    image: freqtradeorg/freqtrade:stable_pi
    restart: unless-stopped
    container_name: bb-rsi-naive-defi
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8082"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/bb-rsi-naive-defi.tradesv3.sqlite
      --config /freqtrade/user_data/bb-rsi-naive-defi.config.json
      --strategy BBRSINaiveStrategy

  bb-rsi-naive-eth-killers:
    image: freqtradeorg/freqtrade:stable_pi
    restart: unless-stopped
    container_name: bb-rsi-naive-eth-killers
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8085:8085"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/bb-rsi-naive-eth-killers.tradesv3.sqlite
      --config /freqtrade/user_data/bb-rsi-naive-eth-killers.config.json
      --strategy BBRSINaiveStrategy

  bb-rsi-naive-old:
    image: freqtradeorg/freqtrade:stable_pi
    restart: unless-stopped
    container_name: bb-rsi-naive-old
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8086:8086"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/bb-rsi-naive-old.tradesv3.sqlite
      --config /freqtrade/user_data/bb-rsi-naive-old.config.json
      --strategy BBRSINaiveStrategy

  bb-rsi-naive-services:
    image: freqtradeorg/freqtrade:stable_pi
    restart: unless-stopped
    container_name: bb-rsi-naive-services
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8087:8087"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/bb-rsi-naive-services.tradesv3.sqlite
      --config /freqtrade/user_data/bb-rsi-naive-services.config.json
      --strategy BBRSINaiveStrategy
